# $Id: Makefile.test-libiter,v 1.2 2007/10/27 03:38:23 kichiki Exp $

CC           = cc
LD           = libtool --mode=link $(CC)

#CFLAGS	     = -Wall -O3 -mtune=pentium
CFLAGS	     = -Wall -pipe -O3 -march=prescott -fomit-frame-pointer\
		-mfpmath=sse\
		-ffast-math\
		-I/usr/local/include\
		-I../../libstokes/src

#ATLAS_LIBS	= \
#	-lg2c -lblas -llapack\
#	-lcblas -lf77blas -latlas
ATLAS_LIBS	= \
	-L/usr/local/lib/gcc-4.2.3 -lgfortran \
	-L/usr/local/lib -lalapack -lf77blas -lcblas -latlas\
	-larpack

LDFLAGS      = 
LIBS         =	../src/libiter.la\
	     	-lm\
		-L/usr/local/lib\
		$(ATLAS_LIBS)

all:		test-libiter

dgetri_c.o:	../../libstokes/src/dgetri_c.c
bench.o:	../../libstokes/src/bench.c

OBJ =	test-libiter.o\
	dgetri_c.o\
	bench.o


test-libiter:	$(OBJ) ../src/libiter.la
	$(LD) $(LDFLAGS) -o test-libiter $(OBJ) $(LIBS)

clean:	
	rm -f *~ *.o test-libiter
